# Generated by Django 3.1.1 on 2020-10-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='phone',
        ),
        migrations.AddField(
            model_name='number',
            name='name',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
