# Generated by Django 3.1.1 on 2020-10-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201006_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='name',
        ),
        migrations.AddField(
            model_name='number',
            name='phone',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
